// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416084007_AddUserPasswordHash")]
    partial class AddUserPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("backend.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Module", "Action")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f66fb4e-ed9a-4f66-9fa7-bb012d0796e4"),
                            Action = "deal.create",
                            Description = "Create sales-process deals",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("cb67e22c-9f3d-8828-5ccd-3b7cbc8b58fa"),
                            Action = "deal.edit_draft",
                            Description = "Edit draft or rejected sales-process deals",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("6da70d6c-f186-252e-6264-180bd89b51ff"),
                            Action = "deal.submit",
                            Description = "Submit sales-process deals for L1 review",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("03369e65-16f6-def9-d2de-0920b486c7d2"),
                            Action = "deal.review_l1",
                            Description = "Review deals at L1",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("659ac5ea-dcd6-70bd-4ecc-2a7f1c14f147"),
                            Action = "deal.edit_amount_l1",
                            Description = "Update deal amount at L1 within guardrails",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("5e01887b-bb75-a2a7-d2b2-d6602217cef9"),
                            Action = "deal.approve_l1",
                            Description = "Approve deals at L1",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("438113cf-6573-bf91-4877-90079901d184"),
                            Action = "deal.reject_l1",
                            Description = "Reject deals at L1",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("4cc743a9-e9ed-4b76-f5a1-42b42f673bab"),
                            Action = "deal.review_l2",
                            Description = "Review deals at L2",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("ef9d663f-9bb6-0687-f293-308b24b26b49"),
                            Action = "deal.approve_l2",
                            Description = "Final approve deals at L2",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("7af0f504-a99c-80bc-556d-83a621fa5b29"),
                            Action = "deal.reject_l2",
                            Description = "Reject deals at L2",
                            Module = "sales-process"
                        },
                        new
                        {
                            Id = new Guid("238cdce1-4d3d-2f54-f859-9ba888c8a263"),
                            Action = "deal.ingest_excel",
                            Description = "Ingest Salesforce Excel dump",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("b40a7a47-b313-75eb-4dd0-65c86560d81a"),
                            Action = "deal.enrich",
                            Description = "Enrich order-governance deal details",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("3472623a-0c6c-b99f-529d-07483abc9e5f"),
                            Action = "deal.submit",
                            Description = "Submit order-governance deal for review",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("dc1f1565-8a15-4b80-2103-d92bb8fc98c7"),
                            Action = "deal.triage",
                            Description = "Triage submitted deals",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("1a967c11-3df0-af79-1dde-9bd31284919e"),
                            Action = "route.configure",
                            Description = "Configure required approver route",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("e804a99f-9f9e-bcac-1103-ad8af3d1e9a9"),
                            Action = "deal.return_to_sales",
                            Description = "Return deal to sales for correction",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("e1c4a91b-d8fe-bbe5-0a07-35285b3d4e20"),
                            Action = "deal.review_required",
                            Description = "Review routed deals as required approver",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1"),
                            Action = "deal.approve",
                            Description = "Approve order-governance deal",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024"),
                            Action = "deal.reject",
                            Description = "Reject order-governance deal",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("9e2686cb-9559-c2c8-61b0-4ce14aad095f"),
                            Action = "final.capture_po",
                            Description = "Capture Actual PO/SAP/Customer order details",
                            Module = "order-governance"
                        },
                        new
                        {
                            Id = new Guid("48628b11-f729-6274-c461-58feb29aa95e"),
                            Action = "final.confirm_order",
                            Description = "Confirm final order execution",
                            Module = "order-governance"
                        });
                });

            modelBuilder.Entity("backend.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            Description = "Sales Process module Sales Manager",
                            Name = "sales-process.sales-manager"
                        },
                        new
                        {
                            Id = new Guid("10222222-2222-2222-2222-222222222222"),
                            Description = "Sales Process module Regional Manager (L1)",
                            Name = "sales-process.regional-manager"
                        },
                        new
                        {
                            Id = new Guid("10333333-3333-3333-3333-333333333333"),
                            Description = "Sales Process module Central Manager (L2)",
                            Name = "sales-process.central-manager"
                        },
                        new
                        {
                            Id = new Guid("20111111-1111-1111-1111-111111111111"),
                            Description = "Order Governance module Sales role",
                            Name = "order-governance.sales"
                        },
                        new
                        {
                            Id = new Guid("20222222-2222-2222-2222-222222222222"),
                            Description = "Order Governance module Reviewer role",
                            Name = "order-governance.reviewer"
                        },
                        new
                        {
                            Id = new Guid("20333333-3333-3333-3333-333333333333"),
                            Description = "Order Governance module Approver role",
                            Name = "order-governance.approver"
                        },
                        new
                        {
                            Id = new Guid("20444444-4444-4444-4444-444444444444"),
                            Description = "Order Governance module CC Manager role",
                            Name = "order-governance.cc-manager"
                        });
                });

            modelBuilder.Entity("backend.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("0f66fb4e-ed9a-4f66-9fa7-bb012d0796e4")
                        },
                        new
                        {
                            RoleId = new Guid("10111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("cb67e22c-9f3d-8828-5ccd-3b7cbc8b58fa")
                        },
                        new
                        {
                            RoleId = new Guid("10111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("6da70d6c-f186-252e-6264-180bd89b51ff")
                        },
                        new
                        {
                            RoleId = new Guid("10222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("03369e65-16f6-def9-d2de-0920b486c7d2")
                        },
                        new
                        {
                            RoleId = new Guid("10222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("659ac5ea-dcd6-70bd-4ecc-2a7f1c14f147")
                        },
                        new
                        {
                            RoleId = new Guid("10222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("5e01887b-bb75-a2a7-d2b2-d6602217cef9")
                        },
                        new
                        {
                            RoleId = new Guid("10222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("438113cf-6573-bf91-4877-90079901d184")
                        },
                        new
                        {
                            RoleId = new Guid("10333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("4cc743a9-e9ed-4b76-f5a1-42b42f673bab")
                        },
                        new
                        {
                            RoleId = new Guid("10333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("ef9d663f-9bb6-0687-f293-308b24b26b49")
                        },
                        new
                        {
                            RoleId = new Guid("10333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("7af0f504-a99c-80bc-556d-83a621fa5b29")
                        },
                        new
                        {
                            RoleId = new Guid("20111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("238cdce1-4d3d-2f54-f859-9ba888c8a263")
                        },
                        new
                        {
                            RoleId = new Guid("20111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("b40a7a47-b313-75eb-4dd0-65c86560d81a")
                        },
                        new
                        {
                            RoleId = new Guid("20111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("3472623a-0c6c-b99f-529d-07483abc9e5f")
                        },
                        new
                        {
                            RoleId = new Guid("20222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("dc1f1565-8a15-4b80-2103-d92bb8fc98c7")
                        },
                        new
                        {
                            RoleId = new Guid("20222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("1a967c11-3df0-af79-1dde-9bd31284919e")
                        },
                        new
                        {
                            RoleId = new Guid("20222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("e804a99f-9f9e-bcac-1103-ad8af3d1e9a9")
                        },
                        new
                        {
                            RoleId = new Guid("20333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("e1c4a91b-d8fe-bbe5-0a07-35285b3d4e20")
                        },
                        new
                        {
                            RoleId = new Guid("20333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1")
                        },
                        new
                        {
                            RoleId = new Guid("20333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024")
                        },
                        new
                        {
                            RoleId = new Guid("20444444-4444-4444-4444-444444444444"),
                            PermissionId = new Guid("9e2686cb-9559-c2c8-61b0-4ce14aad095f")
                        },
                        new
                        {
                            RoleId = new Guid("20444444-4444-4444-4444-444444444444"),
                            PermissionId = new Guid("48628b11-f729-6274-c461-58feb29aa95e")
                        });
                });

            modelBuilder.Entity("backend.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("backend.Entities.RolePermission", b =>
                {
                    b.HasOne("backend.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Entities.UserRole", b =>
                {
                    b.HasOne("backend.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("backend.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("backend.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
