// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("backend.Entities.ApprovalRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VerticalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VerticalId");

                    b.HasIndex("RoleId", "IsActive");

                    b.HasIndex("ModuleId", "RoleId", "VerticalId", "UserId")
                        .IsUnique()
                        .HasFilter("[VerticalId] IS NOT NULL");

                    b.ToTable("ApprovalRoleAssignments", (string)null);
                });

            modelBuilder.Entity("backend.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("EntityName", "ReferenceId");

                    b.HasIndex("ModuleId", "PerformedAtUtc");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("backend.Entities.HorizontalMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HorizontalMaster", (string)null);
                });

            modelBuilder.Entity("backend.Entities.MarginThresholdConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxMarginPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("MinMarginPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VerticalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VerticalId");

                    b.HasIndex("ModuleId", "VerticalId", "IsActive");

                    b.ToTable("MarginThresholdConfig", (string)null);
                });

            modelBuilder.Entity("backend.Entities.MarginThresholdRole", b =>
                {
                    b.Property<Guid>("ThresholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ThresholdId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("MarginThresholdRoles", (string)null);
                });

            modelBuilder.Entity("backend.Entities.ModuleMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ModuleMaster", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Code = "sales-process",
                            CreatedAtUtc = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sales Process"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Code = "order-governance",
                            CreatedAtUtc = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Order Governance"
                        });
                });

            modelBuilder.Entity("backend.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserId", "IsRead", "CreatedAtUtc");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActionDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("VerticalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("VerticalId");

                    b.HasIndex("DealId", "RoleKey")
                        .IsUnique();

                    b.HasIndex("DealId", "Status");

                    b.ToTable("OrderGovernanceApprovals", (string)null);
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceCostBreakup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CostTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CostTypeLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DealId", "CostTypeCode")
                        .IsUnique();

                    b.ToTable("OrderGovernanceCostBreakup", (string)null);
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceDeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ActualPoValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("AmcValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CloseDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ConversionRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CustomerOrderNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPaymentTerm")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("ExternalServiceCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Geo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("HorizontalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InternalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OpportunityName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OpportunityNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OpportunityOwner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("OthersCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OthersValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequiredApprovalsCsv")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SapOrder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ServiceValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorPaymentTerm")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<Guid?>("VerticalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HorizontalId");

                    b.HasIndex("OpportunityNumber");

                    b.HasIndex("VerticalId");

                    b.ToTable("OrderGovernanceDeals", (string)null);
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DealId", "UploadedAtUtc");

                    b.ToTable("OrderGovernanceDocuments", (string)null);
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerPoNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FinalPoValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SapOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("DealId")
                        .IsUnique();

                    b.ToTable("OrderGovernanceExecution", (string)null);
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("ActorRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ActorRoleId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("DealId", "CreatedAtUtc");

                    b.ToTable("OrderGovernanceHistory", (string)null);
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceVersionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggerEvent")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("VerticalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("VerticalId");

                    b.HasIndex("DealId", "ChangedAtUtc");

                    b.HasIndex("DealId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("OrderGovernanceVersionHistory", (string)null);
                });

            modelBuilder.Entity("backend.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Module", "Action")
                        .IsUnique();

                    b.HasIndex("ModuleId", "Action");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f66fb4e-ed9a-4f66-9fa7-bb012d0796e4"),
                            Action = "deal.create",
                            Description = "Create sales-process deals",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.create"
                        },
                        new
                        {
                            Id = new Guid("cb67e22c-9f3d-8828-5ccd-3b7cbc8b58fa"),
                            Action = "deal.edit_draft",
                            Description = "Edit draft or rejected sales-process deals",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.edit_draft"
                        },
                        new
                        {
                            Id = new Guid("6da70d6c-f186-252e-6264-180bd89b51ff"),
                            Action = "deal.submit",
                            Description = "Submit sales-process deals for L1 review",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.submit"
                        },
                        new
                        {
                            Id = new Guid("03369e65-16f6-def9-d2de-0920b486c7d2"),
                            Action = "deal.review_l1",
                            Description = "Review deals at L1",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.review_l1"
                        },
                        new
                        {
                            Id = new Guid("659ac5ea-dcd6-70bd-4ecc-2a7f1c14f147"),
                            Action = "deal.edit_amount_l1",
                            Description = "Update deal amount at L1 within guardrails",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.edit_amount_l1"
                        },
                        new
                        {
                            Id = new Guid("5e01887b-bb75-a2a7-d2b2-d6602217cef9"),
                            Action = "deal.approve_l1",
                            Description = "Approve deals at L1",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.approve_l1"
                        },
                        new
                        {
                            Id = new Guid("438113cf-6573-bf91-4877-90079901d184"),
                            Action = "deal.reject_l1",
                            Description = "Reject deals at L1",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.reject_l1"
                        },
                        new
                        {
                            Id = new Guid("4cc743a9-e9ed-4b76-f5a1-42b42f673bab"),
                            Action = "deal.review_l2",
                            Description = "Review deals at L2",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.review_l2"
                        },
                        new
                        {
                            Id = new Guid("ef9d663f-9bb6-0687-f293-308b24b26b49"),
                            Action = "deal.approve_l2",
                            Description = "Final approve deals at L2",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.approve_l2"
                        },
                        new
                        {
                            Id = new Guid("7af0f504-a99c-80bc-556d-83a621fa5b29"),
                            Action = "deal.reject_l2",
                            Description = "Reject deals at L2",
                            IsActive = true,
                            Module = "sales-process",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "deal.reject_l2"
                        },
                        new
                        {
                            Id = new Guid("238cdce1-4d3d-2f54-f859-9ba888c8a263"),
                            Action = "deal.ingest_excel",
                            Description = "Ingest Salesforce Excel dump",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.ingest_excel"
                        },
                        new
                        {
                            Id = new Guid("b40a7a47-b313-75eb-4dd0-65c86560d81a"),
                            Action = "deal.enrich",
                            Description = "Enrich order-governance deal details",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.enrich"
                        },
                        new
                        {
                            Id = new Guid("3472623a-0c6c-b99f-529d-07483abc9e5f"),
                            Action = "deal.submit",
                            Description = "Submit order-governance deal for review",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.submit"
                        },
                        new
                        {
                            Id = new Guid("dc1f1565-8a15-4b80-2103-d92bb8fc98c7"),
                            Action = "deal.triage",
                            Description = "Triage submitted deals",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.triage"
                        },
                        new
                        {
                            Id = new Guid("1a967c11-3df0-af79-1dde-9bd31284919e"),
                            Action = "route.configure",
                            Description = "Configure required approver route",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "route.configure"
                        },
                        new
                        {
                            Id = new Guid("e804a99f-9f9e-bcac-1103-ad8af3d1e9a9"),
                            Action = "deal.return_to_sales",
                            Description = "Return deal to sales for correction",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.return_to_sales"
                        },
                        new
                        {
                            Id = new Guid("e1c4a91b-d8fe-bbe5-0a07-35285b3d4e20"),
                            Action = "deal.review_required",
                            Description = "Review routed deals as required approver (legacy)",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.review_required"
                        },
                        new
                        {
                            Id = new Guid("e01a7bc6-2b71-44bb-72cf-454e6606d725"),
                            Action = "deal.review_finance",
                            Description = "Act as Finance approver on routed deals",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.review_finance"
                        },
                        new
                        {
                            Id = new Guid("bf21fbd1-89d4-2bbc-a5c2-ce0c17e08891"),
                            Action = "deal.review_legal",
                            Description = "Act as Legal approver on routed deals",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.review_legal"
                        },
                        new
                        {
                            Id = new Guid("cd894c87-2b7a-31be-89b4-874d6f2422d7"),
                            Action = "deal.review_business_head",
                            Description = "Act as Business Head approver on routed deals",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.review_business_head"
                        },
                        new
                        {
                            Id = new Guid("a22373b0-b304-1373-996e-0f8d870bfea1"),
                            Action = "deal.review_scm",
                            Description = "Act as SCM approver on routed deals",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.review_scm"
                        },
                        new
                        {
                            Id = new Guid("4cc44620-1159-20ce-95e1-7acb54bfc0d7"),
                            Action = "deal.review_service_delivery",
                            Description = "Act as Service Delivery approver on routed deals",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.review_service_delivery"
                        },
                        new
                        {
                            Id = new Guid("4edcda42-bb4e-35a3-0f3f-247c26053d43"),
                            Action = "deal.review_pre_sales",
                            Description = "Act as Pre-Sales approver on routed deals",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.review_pre_sales"
                        },
                        new
                        {
                            Id = new Guid("1844d772-0549-7d02-40ca-3e9657679b15"),
                            Action = "deal.manage_documents",
                            Description = "Upload and delete order-governance deal documents",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.manage_documents"
                        },
                        new
                        {
                            Id = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1"),
                            Action = "deal.approve",
                            Description = "Approve order-governance deal",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.approve"
                        },
                        new
                        {
                            Id = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024"),
                            Action = "deal.reject",
                            Description = "Reject order-governance deal",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "deal.reject"
                        },
                        new
                        {
                            Id = new Guid("9e2686cb-9559-c2c8-61b0-4ce14aad095f"),
                            Action = "final.capture_po",
                            Description = "Capture Actual PO/SAP/Customer order details",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "final.capture_po"
                        },
                        new
                        {
                            Id = new Guid("48628b11-f729-6274-c461-58feb29aa95e"),
                            Action = "final.confirm_order",
                            Description = "Confirm final order execution",
                            IsActive = true,
                            Module = "order-governance",
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "final.confirm_order"
                        });
                });

            modelBuilder.Entity("backend.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ModuleId", "Code");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            Code = "sales-manager",
                            Description = "Sales Process module Sales Manager",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "sales-process.sales-manager"
                        },
                        new
                        {
                            Id = new Guid("10222222-2222-2222-2222-222222222222"),
                            Code = "regional-manager",
                            Description = "Sales Process module Regional Manager (L1)",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "sales-process.regional-manager"
                        },
                        new
                        {
                            Id = new Guid("10333333-3333-3333-3333-333333333333"),
                            Code = "central-manager",
                            Description = "Sales Process module Central Manager (L2)",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "sales-process.central-manager"
                        },
                        new
                        {
                            Id = new Guid("20111111-1111-1111-1111-111111111111"),
                            Code = "sales",
                            Description = "Order Governance module Sales role",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.sales"
                        },
                        new
                        {
                            Id = new Guid("20222222-2222-2222-2222-222222222222"),
                            Code = "reviewer",
                            Description = "Order Governance module Reviewer role",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.reviewer"
                        },
                        new
                        {
                            Id = new Guid("20333333-3333-3333-3333-333333333333"),
                            Code = "approver",
                            Description = "Deprecated: use order-governance.approver-* lane roles",
                            IsActive = false,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.approver"
                        },
                        new
                        {
                            Id = new Guid("20444444-4444-4444-4444-444444444444"),
                            Code = "cc-manager",
                            Description = "Order Governance module CC Manager role",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.cc-manager"
                        },
                        new
                        {
                            Id = new Guid("20555555-5555-5555-5555-555555555501"),
                            Code = "approver-finance",
                            Description = "Order Governance Finance approver lane",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.approver-finance"
                        },
                        new
                        {
                            Id = new Guid("20555555-5555-5555-5555-555555555502"),
                            Code = "approver-legal",
                            Description = "Order Governance Legal approver lane",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.approver-legal"
                        },
                        new
                        {
                            Id = new Guid("20555555-5555-5555-5555-555555555503"),
                            Code = "approver-business-head",
                            Description = "Order Governance Business Head approver lane",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.approver-business-head"
                        },
                        new
                        {
                            Id = new Guid("20555555-5555-5555-5555-555555555504"),
                            Code = "approver-scm",
                            Description = "Order Governance SCM approver lane",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.approver-scm"
                        },
                        new
                        {
                            Id = new Guid("20555555-5555-5555-5555-555555555505"),
                            Code = "approver-service-delivery",
                            Description = "Order Governance Service Delivery approver lane",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.approver-service-delivery"
                        },
                        new
                        {
                            Id = new Guid("20555555-5555-5555-5555-555555555506"),
                            Code = "approver-pre-sales",
                            Description = "Order Governance Pre-Sales approver lane",
                            IsActive = true,
                            ModuleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "order-governance.approver-pre-sales"
                        });
                });

            modelBuilder.Entity("backend.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("0f66fb4e-ed9a-4f66-9fa7-bb012d0796e4")
                        },
                        new
                        {
                            RoleId = new Guid("10111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("cb67e22c-9f3d-8828-5ccd-3b7cbc8b58fa")
                        },
                        new
                        {
                            RoleId = new Guid("10111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("6da70d6c-f186-252e-6264-180bd89b51ff")
                        },
                        new
                        {
                            RoleId = new Guid("10222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("03369e65-16f6-def9-d2de-0920b486c7d2")
                        },
                        new
                        {
                            RoleId = new Guid("10222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("659ac5ea-dcd6-70bd-4ecc-2a7f1c14f147")
                        },
                        new
                        {
                            RoleId = new Guid("10222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("5e01887b-bb75-a2a7-d2b2-d6602217cef9")
                        },
                        new
                        {
                            RoleId = new Guid("10222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("438113cf-6573-bf91-4877-90079901d184")
                        },
                        new
                        {
                            RoleId = new Guid("10333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("4cc743a9-e9ed-4b76-f5a1-42b42f673bab")
                        },
                        new
                        {
                            RoleId = new Guid("10333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("ef9d663f-9bb6-0687-f293-308b24b26b49")
                        },
                        new
                        {
                            RoleId = new Guid("10333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("7af0f504-a99c-80bc-556d-83a621fa5b29")
                        },
                        new
                        {
                            RoleId = new Guid("20111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("1844d772-0549-7d02-40ca-3e9657679b15")
                        },
                        new
                        {
                            RoleId = new Guid("20111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("b40a7a47-b313-75eb-4dd0-65c86560d81a")
                        },
                        new
                        {
                            RoleId = new Guid("20111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("3472623a-0c6c-b99f-529d-07483abc9e5f")
                        },
                        new
                        {
                            RoleId = new Guid("20222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("238cdce1-4d3d-2f54-f859-9ba888c8a263")
                        },
                        new
                        {
                            RoleId = new Guid("20222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("1844d772-0549-7d02-40ca-3e9657679b15")
                        },
                        new
                        {
                            RoleId = new Guid("20222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("dc1f1565-8a15-4b80-2103-d92bb8fc98c7")
                        },
                        new
                        {
                            RoleId = new Guid("20222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("1a967c11-3df0-af79-1dde-9bd31284919e")
                        },
                        new
                        {
                            RoleId = new Guid("20222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("e804a99f-9f9e-bcac-1103-ad8af3d1e9a9")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555501"),
                            PermissionId = new Guid("e01a7bc6-2b71-44bb-72cf-454e6606d725")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555501"),
                            PermissionId = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555501"),
                            PermissionId = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555502"),
                            PermissionId = new Guid("bf21fbd1-89d4-2bbc-a5c2-ce0c17e08891")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555502"),
                            PermissionId = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555502"),
                            PermissionId = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555503"),
                            PermissionId = new Guid("cd894c87-2b7a-31be-89b4-874d6f2422d7")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555503"),
                            PermissionId = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555503"),
                            PermissionId = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555504"),
                            PermissionId = new Guid("a22373b0-b304-1373-996e-0f8d870bfea1")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555504"),
                            PermissionId = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555504"),
                            PermissionId = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555505"),
                            PermissionId = new Guid("4cc44620-1159-20ce-95e1-7acb54bfc0d7")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555505"),
                            PermissionId = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555505"),
                            PermissionId = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555506"),
                            PermissionId = new Guid("4edcda42-bb4e-35a3-0f3f-247c26053d43")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555506"),
                            PermissionId = new Guid("15d0aec6-09ed-dbfe-1670-26624381aad1")
                        },
                        new
                        {
                            RoleId = new Guid("20555555-5555-5555-5555-555555555506"),
                            PermissionId = new Guid("ab1e5c52-665c-274f-af5e-7562d8e8e024")
                        },
                        new
                        {
                            RoleId = new Guid("20444444-4444-4444-4444-444444444444"),
                            PermissionId = new Guid("9e2686cb-9559-c2c8-61b0-4ce14aad095f")
                        },
                        new
                        {
                            RoleId = new Guid("20444444-4444-4444-4444-444444444444"),
                            PermissionId = new Guid("48628b11-f729-6274-c461-58feb29aa95e")
                        });
                });

            modelBuilder.Entity("backend.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("backend.Entities.VerticalMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("VerticalMaster", (string)null);
                });

            modelBuilder.Entity("backend.Entities.ApprovalRoleAssignment", b =>
                {
                    b.HasOne("backend.Entities.ModuleMaster", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.VerticalMaster", "Vertical")
                        .WithMany()
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("backend.Entities.AuditLog", b =>
                {
                    b.HasOne("backend.Entities.ModuleMaster", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.AppUser", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Module");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("backend.Entities.MarginThresholdConfig", b =>
                {
                    b.HasOne("backend.Entities.ModuleMaster", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.VerticalMaster", "Vertical")
                        .WithMany()
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Module");

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("backend.Entities.MarginThresholdRole", b =>
                {
                    b.HasOne("backend.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.MarginThresholdConfig", "Threshold")
                        .WithMany("Roles")
                        .HasForeignKey("ThresholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Threshold");
                });

            modelBuilder.Entity("backend.Entities.Notification", b =>
                {
                    b.HasOne("backend.Entities.ModuleMaster", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceApproval", b =>
                {
                    b.HasOne("backend.Entities.AppUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.OrderGovernanceDeal", "Deal")
                        .WithMany("Approvals")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.VerticalMaster", "Vertical")
                        .WithMany()
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUser");

                    b.Navigation("Deal");

                    b.Navigation("Role");

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceCostBreakup", b =>
                {
                    b.HasOne("backend.Entities.OrderGovernanceDeal", "Deal")
                        .WithMany("CostBreakup")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceDeal", b =>
                {
                    b.HasOne("backend.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.HorizontalMaster", "Horizontal")
                        .WithMany()
                        .HasForeignKey("HorizontalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.VerticalMaster", "Vertical")
                        .WithMany()
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Horizontal");

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceDocument", b =>
                {
                    b.HasOne("backend.Entities.OrderGovernanceDeal", "Deal")
                        .WithMany("Documents")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceExecution", b =>
                {
                    b.HasOne("backend.Entities.AppUser", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.OrderGovernanceDeal", "Deal")
                        .WithOne("Execution")
                        .HasForeignKey("backend.Entities.OrderGovernanceExecution", "DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceHistory", b =>
                {
                    b.HasOne("backend.Entities.Role", "ActorRoleRef")
                        .WithMany()
                        .HasForeignKey("ActorRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.AppUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.OrderGovernanceApproval", "Approval")
                        .WithMany()
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.OrderGovernanceDeal", "Deal")
                        .WithMany("History")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorRoleRef");

                    b.Navigation("ActorUser");

                    b.Navigation("Approval");

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceVersionHistory", b =>
                {
                    b.HasOne("backend.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.OrderGovernanceDeal", "Deal")
                        .WithMany("VersionHistory")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.VerticalMaster", "Vertical")
                        .WithMany()
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangedByUser");

                    b.Navigation("Deal");

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("backend.Entities.Permission", b =>
                {
                    b.HasOne("backend.Entities.ModuleMaster", "ModuleRef")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModuleRef");
                });

            modelBuilder.Entity("backend.Entities.Role", b =>
                {
                    b.HasOne("backend.Entities.ModuleMaster", "Module")
                        .WithMany("Roles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Module");
                });

            modelBuilder.Entity("backend.Entities.RolePermission", b =>
                {
                    b.HasOne("backend.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Entities.UserRole", b =>
                {
                    b.HasOne("backend.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("backend.Entities.MarginThresholdConfig", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("backend.Entities.ModuleMaster", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("backend.Entities.OrderGovernanceDeal", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("CostBreakup");

                    b.Navigation("Documents");

                    b.Navigation("Execution");

                    b.Navigation("History");

                    b.Navigation("VersionHistory");
                });

            modelBuilder.Entity("backend.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("backend.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
